# RUSH Sales Analysis

### Data Collection

In [1]:
import os

folder_path = "./sales_data" # local
csv_files = []

for filename in os.listdir(folder_path):
    if filename.endswith(".csv"):
        csv_files.append(filename)

print(len(csv_files))
csv_files

3

['TABLE_PRODUCTS_885.csv', 'TABLE_RETAILER_885.csv', 'TABLE_SALES_885.csv']

### Data Preparation

In [2]:
import pandas as pd

dfs = {}

for csv in csv_files:
  file_path = os.path.join(folder_path, csv)
  file_name = os.path.splitext(csv)[0]
  dfs[file_name] = pd.read_csv(file_path)

dfs

{'TABLE_PRODUCTS_885':          PRODUCT_ID|PRODUCT_NAME
 0      020|Men's Street Footwear
 1    030|Men's Athletic Footwear
 2    120|Women's Street Footwear
 3  130|Women's Athletic Footwear
 4              040|Men's Apparel
 5            140|Women's Apparel,
 'TABLE_RETAILER_885':     RETAILER_ID   RETAILER     REGION          STATE            CITY
 0      A00MOHCO     Amazon    Midwest           Ohio        Columbus
 1      A00NMAPO     Amazon  Northeast          Maine        Portland
 2      A00NMABO     Amazon  Northeast  Massachusetts          Boston
 3      A00NNEMA     Amazon  Northeast  New Hampshire      Manchester
 4      A00NVEBU     Amazon  Northeast        Vermont      Burlington
 ..          ...        ...        ...            ...             ...
 105    W00WIDBO  West Gear       West          Idaho           Boise
 106    W00WNELA  West Gear       West         Nevada       Las Vegas
 107    W00WORPO  West Gear       West         Oregon        Portland
 108    W00WUTSA  West Gear       West           Utah  Salt Lake City
 109    W00WWASE  West Gear       West     Washington         Seattle

 [110 rows x 5 columns],
 'TABLE_SALES_885':       ORDER_ID RETAILER_ID INVOICE_DATE  MONTH  DAY  YEAR  PRODUCT_ID  \
 0            1    A00MOHCO     1/1/2020      1    1  2020          20
 1            7    A00MOHCO     1/7/2020      1    7  2020          20
 2           13    A00MOHCO    1/25/2020      1   25  2020          20
 3           19    A00MOHCO    1/31/2020      1   31  2020          20
 4           25    A00MOHCO     2/6/2020      2    6  2020          20
 ...        ...         ...          ...    ...  ...   ...         ...
 9643      9621    W00WIDBO    9/17/2021      9   17  2021         140
 9644      9627    W00WIDBO   10/19/2021     10   19  2021         140
 9645      9633    W00WIDBO   11/18/2021     11   18  2021         140
 9646      9639    W00WIDBO   12/17/2021     12   17  2021         140
 9647      9645    W00WIDBO    1/24/2021      1   24  2021         140

       PRICE_PER_UNIT UNITS_SOLD  OPERATING_MARGIN SALES_METHOD
 0               50.0       1200              0.50     In-store
 1               50.0       1250              0.50     In-store
 2               50.0       1220              0.50       Outlet
 3               50.0       1200              0.50       Outlet
 4               60.0       1220              0.50       Outlet
 ...              ...        ...               ...          ...
 9643            53.0        104              0.37       Outlet
 9644            64.0         90              0.39       Outlet
 9645            61.0        120              0.41       Outlet
 9646            61.0        144              0.40       Outlet
 9647            41.0        105              0.32       Outlet

 [9648 rows x 11 columns]}

### Data Inspection

In [3]:
dfs['TABLE_SALES_885'].head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet

In [4]:
dfs['TABLE_SALES_885'].describe()

,ORDER_ID,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,OPERATING_MARGIN
count,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9646.000000,9648.000000
mean,4824.500000,6.458126,14.696310,2020.865050,79.975124,55.575264,0.422991
std,2785.282032,3.454799,7.348019,0.341688,50.668992,1017.819943,0.097197
min,1.000000,1.000000,1.000000,2020.000000,20.000000,7.000000,0.100000
25%,2412.750000,3.000000,9.000000,2021.000000,30.000000,35.000000,0.350000
50%,4824.500000,6.000000,15.000000,2021.000000,40.000000,45.000000,0.410000
75%,7236.250000,9.000000,21.000000,2021.000000,130.000000,55.000000,0.490000
max,9648.000000,12.000000,31.000000,2021.000000,140.000000,99999.000000,0.800000

In [5]:
dfs['TABLE_SALES_885'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDER_ID          9648 non-null   int64
 1   RETAILER_ID       9648 non-null   object
 2   INVOICE_DATE      9648 non-null   object
 3   MONTH             9648 non-null   int64
 4   DAY               9648 non-null   int64
 5   YEAR              9648 non-null   int64
 6   PRODUCT_ID        9648 non-null   int64
 7   PRICE_PER_UNIT    9646 non-null   float64
 8   UNITS_SOLD        9648 non-null   object
 9   OPERATING_MARGIN  9648 non-null   float64
 10  SALES_METHOD      9648 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 829.3+ KB

In [6]:
dfs['TABLE_RETAILER_885'].head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

Retailer ID contains data according to every other field

In [7]:
dfs['TABLE_RETAILER_885']['RETAILER'].unique()

array(['Amazon', 'Foot Locker', "Kohl's", 'Sports Direct', 'Walmart',
       'West Gear'], dtype=object)

In [8]:
dfs['TABLE_RETAILER_885'][dfs['TABLE_RETAILER_885']['RETAILER'] == "Kohl's"]

   RETAILER_ID RETAILER     REGION       STATE           CITY
42    K00MKAWI   Kohl's    Midwest      Kansas        Wichita
43    K00MMIMI   Kohl's    Midwest   Minnesota    Minneapolis
44    K00MMOBI   Kohl's    Midwest     Montana       Billings
45    K00NDEWI   Kohl's  Northeast    Delaware     Wilmington
46    K00NNENE   Kohl's  Northeast  New Jersey         Newark
47    K00NNEAL   Kohl's  Northeast    New York         Albany
48    K00SOKOK   Kohl's      South    Oklahoma  Oklahoma City
49    K00WARPH   Kohl's       West     Arizona        Phoenix
50    K00WCALO   Kohl's       West  California    Los Angeles
51    K00WCASA   Kohl's       West  California  San Francisco
52    K00WNEAL   Kohl's       West  New Mexico    Albuquerque
53    K00WWYCH   Kohl's       West     Wyoming       Cheyenne

In [9]:
dfs['TABLE_RETAILER_885'].nunique()

RETAILER_ID    106
RETAILER         6
REGION           5
STATE           50
CITY            52
dtype: int64

In [10]:
dfs['TABLE_PRODUCTS_885'].head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [11]:
dfs['TABLE_PRODUCTS_885'].dtypes

PRODUCT_ID|PRODUCT_NAME    object
dtype: object

### Data Cleaning

- Drop redundant data
- Map product IDs
- Recalculate pricing

In [12]:
dfs['TABLE_SALES_885']['INVOICE_DATE']

0         1/1/2020
1         1/7/2020
2        1/25/2020
3        1/31/2020
4         2/6/2020
           ...
9643     9/17/2021
9644    10/19/2021
9645    11/18/2021
9646    12/17/2021
9647     1/24/2021
Name: INVOICE_DATE, Length: 9648, dtype: object

In [13]:
full_date_string = (
    dfs["TABLE_SALES_885"]["MONTH"].astype(str)
    + "/"
    + dfs["TABLE_SALES_885"]["DAY"].astype(str)
    + "/"
    + dfs["TABLE_SALES_885"]["YEAR"].astype(str)
)

dfs["TABLE_SALES_885"]["invoice_date_string"] = pd.to_datetime(full_date_string, format="%m/%d/%Y")
dfs["TABLE_SALES_885"]

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,invoice_date_string
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.50,In-store,2020-01-01
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.50,In-store,2020-01-07
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.50,Outlet,2020-01-25
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.50,Outlet,2020-01-31
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.50,Outlet,2020-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...
9643,9621,W00WIDBO,9/17/2021,9,17,2021,140,53.0,104,0.37,Outlet,2021-09-17
9644,9627,W00WIDBO,10/19/2021,10,19,2021,140,64.0,90,0.39,Outlet,2021-10-19
9645,9633,W00WIDBO,11/18/2021,11,18,2021,140,61.0,120,0.41,Outlet,2021-11-18
9646,9639,W00WIDBO,12/17/2021,12,17,2021,140,61.0,144,0.40,Outlet,2021-12-17
9647,9645,W00WIDBO,1/24/2021,1,24,2021,140,41.0,105,0.32,Outlet,2021-01-24

In [14]:
dfs['TABLE_SALES_885']['INVOICE_DATE_DT'] = pd.to_datetime(dfs['TABLE_SALES_885']['INVOICE_DATE'], format="%m/%d/%Y", errors="coerce")
dfs['TABLE_SALES_885']

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,invoice_date_string,INVOICE_DATE_DT
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.50,In-store,2020-01-01,2020-01-01
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.50,In-store,2020-01-07,2020-01-07
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.50,Outlet,2020-01-25,2020-01-25
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.50,Outlet,2020-01-31,2020-01-31
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.50,Outlet,2020-02-06,2020-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,9621,W00WIDBO,9/17/2021,9,17,2021,140,53.0,104,0.37,Outlet,2021-09-17,2021-09-17
9644,9627,W00WIDBO,10/19/2021,10,19,2021,140,64.0,90,0.39,Outlet,2021-10-19,2021-10-19
9645,9633,W00WIDBO,11/18/2021,11,18,2021,140,61.0,120,0.41,Outlet,2021-11-18,2021-11-18
9646,9639,W00WIDBO,12/17/2021,12,17,2021,140,61.0,144,0.40,Outlet,2021-12-17,2021-12-17
9647,9645,W00WIDBO,1/24/2021,1,24,2021,140,41.0,105,0.32,Outlet,2021-01-24,2021-01-24

In [15]:
date_mismatches = dfs['TABLE_SALES_885']['invoice_date_string'].equals(dfs['TABLE_SALES_885']['INVOICE_DATE_DT']) # None

In [16]:
dfs['TABLE_SALES_885']['INVOICE_DATE_VERIFIED'] = dfs['TABLE_SALES_885']['INVOICE_DATE_DT']

In [17]:
dfs['TABLE_SALES_885'].drop(columns=['INVOICE_DATE', 'MONTH', 'DAY', 'YEAR', 'invoice_date_string', 'INVOICE_DATE_DT'], inplace=True)

In [18]:
dfs['TABLE_PRODUCTS_885'].head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [19]:
col_name = dfs["TABLE_PRODUCTS_885"].columns[0]

dfs["TABLE_PRODUCTS_885"][["PRODUCT_ID", "PRODUCT_NAME"]] = dfs[
    "TABLE_PRODUCTS_885"
][col_name].str.split("|", expand=True)

dfs["TABLE_PRODUCTS_885"] = dfs["TABLE_PRODUCTS_885"].drop(columns=[col_name])

In [20]:
dfs['TABLE_PRODUCTS_885'].head()

  PRODUCT_ID               PRODUCT_NAME
0        020      Men's Street Footwear
1        030    Men's Athletic Footwear
2        120    Women's Street Footwear
3        130  Women's Athletic Footwear
4        040              Men's Apparel

In [21]:
dfs['TABLE_PRODUCTS_885']['PRODUCT_ID'] = pd.to_numeric(dfs['TABLE_PRODUCTS_885']['PRODUCT_ID'], errors='coerce')

In [22]:
product_map = dict(
    zip(dfs["TABLE_PRODUCTS_885"]["PRODUCT_ID"], dfs["TABLE_PRODUCTS_885"]["PRODUCT_NAME"])
)

Sales:
-  PK: ORDER ID
- FK: RETAILER ID
- FK: PRODUCT ID

In [23]:
df_combined = dfs['TABLE_SALES_885'].merge(dfs['TABLE_RETAILER_885'], on='RETAILER_ID', how='left')

In [24]:
df_combined['PRODUCT_NAME'] = df_combined['PRODUCT_ID'].map(product_map)

In [25]:
df_combined.head()

,ORDER_ID,RETAILER_ID,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,INVOICE_DATE_VERIFIED,RETAILER,REGION,STATE,CITY,PRODUCT_NAME
0,1,A00MOHCO,20,50.0,1200,0.5,In-store,2020-01-01,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
1,7,A00MOHCO,20,50.0,1250,0.5,In-store,2020-01-07,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
2,13,A00MOHCO,20,50.0,1220,0.5,Outlet,2020-01-25,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
3,19,A00MOHCO,20,50.0,1200,0.5,Outlet,2020-01-31,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
4,25,A00MOHCO,20,60.0,1220,0.5,Outlet,2020-02-06,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear

## TODO

### Analysis

### Model Preparation

### Modeling

### Interpretation

## Summary