# RUSH Sales Analysis

### Data Collection

In [239]:
import os

folder_path = "./sales_data" # local
csv_files = []

for filename in os.listdir(folder_path):
    if filename.endswith(".csv"):
        csv_files.append(filename)

print(len(csv_files))
csv_files

3

['TABLE_PRODUCTS_885.csv', 'TABLE_RETAILER_885.csv', 'TABLE_SALES_885.csv']

### Data Preparation

In [240]:
import pandas as pd

dfs = {}

for csv in csv_files:
  file_path = os.path.join(folder_path, csv)
  file_name = os.path.splitext(csv)[0]
  dfs[file_name] = pd.read_csv(file_path)

dfs

{'TABLE_PRODUCTS_885':          PRODUCT_ID|PRODUCT_NAME
 0      020|Men's Street Footwear
 1    030|Men's Athletic Footwear
 2    120|Women's Street Footwear
 3  130|Women's Athletic Footwear
 4              040|Men's Apparel
 5            140|Women's Apparel,
 'TABLE_RETAILER_885':     RETAILER_ID   RETAILER     REGION          STATE            CITY
 0      A00MOHCO     Amazon    Midwest           Ohio        Columbus
 1      A00NMAPO     Amazon  Northeast          Maine        Portland
 2      A00NMABO     Amazon  Northeast  Massachusetts          Boston
 3      A00NNEMA     Amazon  Northeast  New Hampshire      Manchester
 4      A00NVEBU     Amazon  Northeast        Vermont      Burlington
 ..          ...        ...        ...            ...             ...
 105    W00WIDBO  West Gear       West          Idaho           Boise
 106    W00WNELA  West Gear       West         Nevada       Las Vegas
 107    W00WORPO  West Gear       West         Oregon        Portland
 108    W00WUTSA  West Gear       West           Utah  Salt Lake City
 109    W00WWASE  West Gear       West     Washington         Seattle

 [110 rows x 5 columns],
 'TABLE_SALES_885':       ORDER_ID RETAILER_ID INVOICE_DATE  MONTH  DAY  YEAR  PRODUCT_ID  \
 0            1    A00MOHCO     1/1/2020      1    1  2020          20
 1            7    A00MOHCO     1/7/2020      1    7  2020          20
 2           13    A00MOHCO    1/25/2020      1   25  2020          20
 3           19    A00MOHCO    1/31/2020      1   31  2020          20
 4           25    A00MOHCO     2/6/2020      2    6  2020          20
 ...        ...         ...          ...    ...  ...   ...         ...
 9643      9621    W00WIDBO    9/17/2021      9   17  2021         140
 9644      9627    W00WIDBO   10/19/2021     10   19  2021         140
 9645      9633    W00WIDBO   11/18/2021     11   18  2021         140
 9646      9639    W00WIDBO   12/17/2021     12   17  2021         140
 9647      9645    W00WIDBO    1/24/2021      1   24  2021         140

       PRICE_PER_UNIT UNITS_SOLD  OPERATING_MARGIN SALES_METHOD
 0               50.0       1200              0.50     In-store
 1               50.0       1250              0.50     In-store
 2               50.0       1220              0.50       Outlet
 3               50.0       1200              0.50       Outlet
 4               60.0       1220              0.50       Outlet
 ...              ...        ...               ...          ...
 9643            53.0        104              0.37       Outlet
 9644            64.0         90              0.39       Outlet
 9645            61.0        120              0.41       Outlet
 9646            61.0        144              0.40       Outlet
 9647            41.0        105              0.32       Outlet

 [9648 rows x 11 columns]}

### Data Inspection

In [241]:
dfs['TABLE_SALES_885'].head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet

In [242]:
dfs['TABLE_SALES_885'].describe()

,ORDER_ID,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,OPERATING_MARGIN
count,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9646.000000,9648.000000
mean,4824.500000,6.458126,14.696310,2020.865050,79.975124,55.575264,0.422991
std,2785.282032,3.454799,7.348019,0.341688,50.668992,1017.819943,0.097197
min,1.000000,1.000000,1.000000,2020.000000,20.000000,7.000000,0.100000
25%,2412.750000,3.000000,9.000000,2021.000000,30.000000,35.000000,0.350000
50%,4824.500000,6.000000,15.000000,2021.000000,40.000000,45.000000,0.410000
75%,7236.250000,9.000000,21.000000,2021.000000,130.000000,55.000000,0.490000
max,9648.000000,12.000000,31.000000,2021.000000,140.000000,99999.000000,0.800000

In [243]:
dfs['TABLE_SALES_885'].info()

<class 'pandas.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDER_ID          9648 non-null   int64
 1   RETAILER_ID       9648 non-null   str
 2   INVOICE_DATE      9648 non-null   str
 3   MONTH             9648 non-null   int64
 4   DAY               9648 non-null   int64
 5   YEAR              9648 non-null   int64
 6   PRODUCT_ID        9648 non-null   int64
 7   PRICE_PER_UNIT    9646 non-null   float64
 8   UNITS_SOLD        9648 non-null   str
 9   OPERATING_MARGIN  9648 non-null   float64
 10  SALES_METHOD      9648 non-null   str
dtypes: float64(2), int64(5), str(4)
memory usage: 829.3 KB

In [244]:
dfs['TABLE_RETAILER_885'].head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

Retailer ID contains data according to every other field

In [245]:
dfs['TABLE_RETAILER_885']['RETAILER'].unique()

<StringArray>
['Amazon', 'Foot Locker', 'Kohl's', 'Sports Direct', 'Walmart', 'West Gear']
Length: 6, dtype: str

In [246]:
dfs['TABLE_RETAILER_885'][dfs['TABLE_RETAILER_885']['RETAILER'] == "Kohl's"]

   RETAILER_ID RETAILER     REGION       STATE           CITY
42    K00MKAWI   Kohl's    Midwest      Kansas        Wichita
43    K00MMIMI   Kohl's    Midwest   Minnesota    Minneapolis
44    K00MMOBI   Kohl's    Midwest     Montana       Billings
45    K00NDEWI   Kohl's  Northeast    Delaware     Wilmington
46    K00NNENE   Kohl's  Northeast  New Jersey         Newark
47    K00NNEAL   Kohl's  Northeast    New York         Albany
48    K00SOKOK   Kohl's      South    Oklahoma  Oklahoma City
49    K00WARPH   Kohl's       West     Arizona        Phoenix
50    K00WCALO   Kohl's       West  California    Los Angeles
51    K00WCASA   Kohl's       West  California  San Francisco
52    K00WNEAL   Kohl's       West  New Mexico    Albuquerque
53    K00WWYCH   Kohl's       West     Wyoming       Cheyenne

In [247]:
dfs['TABLE_RETAILER_885'].nunique()

RETAILER_ID    106
RETAILER         6
REGION           5
STATE           50
CITY            52
dtype: int64

In [248]:
dfs['TABLE_PRODUCTS_885'].head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [249]:
dfs['TABLE_PRODUCTS_885'].dtypes

PRODUCT_ID|PRODUCT_NAME    str
dtype: object

### Data Cleaning

- Drop redundant data
- Convert data types
- Map product IDs
- Handling outliers
    - Trimming
    - Winsorize
    - Transform
    - Impute

In [250]:
dfs['TABLE_SALES_885'] = dfs['TABLE_SALES_885'].drop_duplicates(
    subset=['ORDER_ID'], 
    keep='first', 
    ignore_index=True
)

In [251]:
dfs['TABLE_SALES_885']['INVOICE_DATE']

0         1/1/2020
1         1/7/2020
2        1/25/2020
3        1/31/2020
4         2/6/2020
           ...
9643     9/17/2021
9644    10/19/2021
9645    11/18/2021
9646    12/17/2021
9647     1/24/2021
Name: INVOICE_DATE, Length: 9648, dtype: str

In [252]:
full_date_string = (
    dfs["TABLE_SALES_885"]["MONTH"].astype(str)
    + "/"
    + dfs["TABLE_SALES_885"]["DAY"].astype(str)
    + "/"
    + dfs["TABLE_SALES_885"]["YEAR"].astype(str)
)

dfs["TABLE_SALES_885"]["invoice_date_string"] = pd.to_datetime(full_date_string, format="%m/%d/%Y")
dfs["TABLE_SALES_885"]

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,invoice_date_string
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.50,In-store,2020-01-01
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.50,In-store,2020-01-07
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.50,Outlet,2020-01-25
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.50,Outlet,2020-01-31
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.50,Outlet,2020-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...
9643,9621,W00WIDBO,9/17/2021,9,17,2021,140,53.0,104,0.37,Outlet,2021-09-17
9644,9627,W00WIDBO,10/19/2021,10,19,2021,140,64.0,90,0.39,Outlet,2021-10-19
9645,9633,W00WIDBO,11/18/2021,11,18,2021,140,61.0,120,0.41,Outlet,2021-11-18
9646,9639,W00WIDBO,12/17/2021,12,17,2021,140,61.0,144,0.40,Outlet,2021-12-17
9647,9645,W00WIDBO,1/24/2021,1,24,2021,140,41.0,105,0.32,Outlet,2021-01-24

In [253]:
dfs['TABLE_SALES_885']['INVOICE_DATE_DT'] = pd.to_datetime(dfs['TABLE_SALES_885']['INVOICE_DATE'], format="%m/%d/%Y", errors="coerce")
dfs['TABLE_SALES_885']

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,invoice_date_string,INVOICE_DATE_DT
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.50,In-store,2020-01-01,2020-01-01
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.50,In-store,2020-01-07,2020-01-07
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.50,Outlet,2020-01-25,2020-01-25
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.50,Outlet,2020-01-31,2020-01-31
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.50,Outlet,2020-02-06,2020-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,9621,W00WIDBO,9/17/2021,9,17,2021,140,53.0,104,0.37,Outlet,2021-09-17,2021-09-17
9644,9627,W00WIDBO,10/19/2021,10,19,2021,140,64.0,90,0.39,Outlet,2021-10-19,2021-10-19
9645,9633,W00WIDBO,11/18/2021,11,18,2021,140,61.0,120,0.41,Outlet,2021-11-18,2021-11-18
9646,9639,W00WIDBO,12/17/2021,12,17,2021,140,61.0,144,0.40,Outlet,2021-12-17,2021-12-17
9647,9645,W00WIDBO,1/24/2021,1,24,2021,140,41.0,105,0.32,Outlet,2021-01-24,2021-01-24

In [254]:
date_mismatches = dfs['TABLE_SALES_885']['invoice_date_string'].equals(dfs['TABLE_SALES_885']['INVOICE_DATE_DT']) # None

In [255]:
dfs['TABLE_SALES_885']['INVOICE_DATE_VERIFIED'] = dfs['TABLE_SALES_885']['INVOICE_DATE_DT']

In [256]:
dfs['TABLE_SALES_885'].drop(columns=['INVOICE_DATE', 'MONTH', 'DAY', 'YEAR', 'invoice_date_string', 'INVOICE_DATE_DT'], inplace=True)

In [257]:
dfs['TABLE_SALES_885']['UNITS_SOLD'] = pd.to_numeric(dfs['TABLE_SALES_885']['UNITS_SOLD'], errors='coerce')
dfs['TABLE_SALES_885']['UNITS_SOLD'].dtype

dtype('float64')

In [258]:
dfs['TABLE_PRODUCTS_885'].head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [259]:
col_name = dfs["TABLE_PRODUCTS_885"].columns[0]

dfs["TABLE_PRODUCTS_885"][["PRODUCT_ID", "PRODUCT_NAME"]] = dfs[
    "TABLE_PRODUCTS_885"
][col_name].str.split("|", expand=True)

dfs["TABLE_PRODUCTS_885"] = dfs["TABLE_PRODUCTS_885"].drop(columns=[col_name])

In [260]:
dfs['TABLE_PRODUCTS_885'].head()

  PRODUCT_ID               PRODUCT_NAME
0        020      Men's Street Footwear
1        030    Men's Athletic Footwear
2        120    Women's Street Footwear
3        130  Women's Athletic Footwear
4        040              Men's Apparel

In [261]:
dfs['TABLE_PRODUCTS_885']['PRODUCT_ID'] = pd.to_numeric(dfs['TABLE_PRODUCTS_885']['PRODUCT_ID'], errors='coerce')

In [262]:
product_map = dict(
    zip(dfs["TABLE_PRODUCTS_885"]["PRODUCT_ID"], dfs["TABLE_PRODUCTS_885"]["PRODUCT_NAME"])
)

Sales:
-  PK: ORDER ID
- FK: RETAILER ID
- FK: PRODUCT ID

In [263]:
df_combined = dfs['TABLE_SALES_885'].merge(dfs['TABLE_RETAILER_885'], on='RETAILER_ID', how='left')

In [264]:
df_combined['PRODUCT_NAME'] = df_combined['PRODUCT_ID'].map(product_map)

In [265]:
df_combined.head(20)

,ORDER_ID,RETAILER_ID,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,INVOICE_DATE_VERIFIED,RETAILER,REGION,STATE,CITY,PRODUCT_NAME
0,1,A00MOHCO,20,50.0,1200.0,0.50,In-store,2020-01-01,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
1,7,A00MOHCO,20,50.0,1250.0,0.50,In-store,2020-01-07,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
2,13,A00MOHCO,20,50.0,1220.0,0.50,Outlet,2020-01-25,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
3,19,A00MOHCO,20,50.0,1200.0,0.50,Outlet,2020-01-31,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
4,25,A00MOHCO,20,60.0,1220.0,0.50,Outlet,2020-02-06,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
5,31,A00MOHCO,20,60.0,1250.0,0.50,Outlet,2020-03-04,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
6,37,A00MOHCO,20,60.0,1275.0,0.50,Outlet,2020-03-10,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
7,43,A00MOHCO,20,60.0,1250.0,0.50,Outlet,2020-03-16,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
8,49,A00MOHCO,20,60.0,1200.0,0.50,Outlet,2020-04-19,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
9,57,A00MOHCO,20,65.0,1150.0,0.50,Outlet,2020-04-27,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
10,63,A00MOHCO,20,65.0,1200.0,0.50,Outlet,2020-05-03,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
11,69,A00MOHCO,20,25.0,900.0,0.35,Outlet,2020-07-19,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
12,75,A00MOHCO,20,25.0,850.0,0.35,Outlet,2020-07-25,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
13,81,A00MOHCO,20,30.0,875.0,0.35,Outlet,2020-07-31,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
14,87,A00MOHCO,20,30.0,900.0,0.35,Outlet,2020-08-06,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
15,93,A00MOHCO,20,30.0,925.0,0.35,Outlet,2020-08-12,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
16,99,A00MOHCO,20,40.0,950.0,0.35,Outlet,2020-08-18,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
17,105,A00MOHCO,20,40.0,950.0,0.35,Outlet,2020-08-24,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
18,111,A00MOHCO,20,40.0,925.0,0.35,Outlet,2020-08-30,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear
19,117,A00MOHCO,20,45.0,850.0,0.35,Outlet,2020-09-05,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear

In [266]:
df_combined.describe()

,ORDER_ID,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,INVOICE_DATE_VERIFIED
count,10271.000000,10271.000000,10269.000000,10269.000000,10271.000000,10271
mean,4970.630903,80.001947,54.575324,246.638232,0.426380,2021-05-13 12:00:54.678220
min,1.000000,20.000000,7.000000,0.000000,0.100000,2020-01-01 00:00:00
25%,2568.500000,30.000000,35.000000,100.000000,0.350000,2021-02-18 00:00:00
50%,5136.000000,120.000000,45.000000,173.000000,0.420000,2021-06-05 00:00:00
75%,7236.000000,130.000000,55.000000,325.000000,0.500000,2021-09-17 00:00:00
max,9648.000000,140.000000,99999.000000,1275.000000,0.800000,2021-12-31 00:00:00
std,2770.737186,50.671441,986.473924,211.881078,0.096018,NaN

In [267]:
error_mask = (df_combined['PRICE_PER_UNIT'].isna()) | (df_combined['PRICE_PER_UNIT'] == 99999.0)
df_clean = df_combined[~error_mask].copy()

In [268]:
# Calculate Q1, Q3, and upper limits per category
q1 = df_clean.groupby('PRODUCT_NAME')['PRICE_PER_UNIT'].quantile(0.25)
q3 = df_clean.groupby('PRODUCT_NAME')['PRICE_PER_UNIT'].quantile(0.75)
upper_limit = q3 + 1.5 * (q3 - q1)

# Map the limits to each row in the dataframe and filter
row_limits = df_clean['PRODUCT_NAME'].map(upper_limit)

# Winsorize by clipping the column between 0 and the mapped limits
df_clean['PRICE_PER_UNIT_winsorized'] = df_clean['PRICE_PER_UNIT'].clip(lower=0, upper=row_limits)

df_clean.head()

,ORDER_ID,RETAILER_ID,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD,INVOICE_DATE_VERIFIED,RETAILER,REGION,STATE,CITY,PRODUCT_NAME,PRICE_PER_UNIT_winsorized
0,1,A00MOHCO,20,50.0,1200.0,0.5,In-store,2020-01-01,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear,50.0
1,7,A00MOHCO,20,50.0,1250.0,0.5,In-store,2020-01-07,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear,50.0
2,13,A00MOHCO,20,50.0,1220.0,0.5,Outlet,2020-01-25,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear,50.0
3,19,A00MOHCO,20,50.0,1200.0,0.5,Outlet,2020-01-31,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear,50.0
4,25,A00MOHCO,20,60.0,1220.0,0.5,Outlet,2020-02-06,Amazon,Midwest,Ohio,Columbus,Men's Street Footwear,60.0

In [269]:
prices_comparison = df_clean[
    (df_clean['PRICE_PER_UNIT'] != df_clean['PRICE_PER_UNIT_winsorized']) & 
    df_clean['PRICE_PER_UNIT'].notna()
]
prices_comparison[['PRODUCT_NAME', 'PRICE_PER_UNIT', 'PRICE_PER_UNIT_winsorized']].head(20)

                 PRODUCT_NAME  PRICE_PER_UNIT  PRICE_PER_UNIT_winsorized
233     Men's Street Footwear            90.0                       86.5
234     Men's Street Footwear            95.0                       86.5
270     Men's Street Footwear            90.0                       86.5
318     Men's Street Footwear            90.0                       86.5
329     Men's Street Footwear            90.0                       86.5
330     Men's Street Footwear            95.0                       86.5
883     Men's Street Footwear            87.0                       86.5
1825  Men's Athletic Footwear            80.0                       75.0
1826  Men's Athletic Footwear            85.0                       75.0
1827  Men's Athletic Footwear            80.0                       75.0
1831  Men's Athletic Footwear            85.0                       75.0
1934  Men's Athletic Footwear            85.0                       75.0
1939  Men's Athletic Footwear            85.0                       75.0
1946  Men's Athletic Footwear            95.0                       75.0
1947  Men's Athletic Footwear            85.0                       75.0
1951  Men's Athletic Footwear            85.0                       75.0
1982  Men's Athletic Footwear            90.0                       75.0
1983  Men's Athletic Footwear            80.0                       75.0
2030  Men's Athletic Footwear            90.0                       75.0
2031  Men's Athletic Footwear            80.0                       75.0

### Analysis

##### Metrics

| Metric | Formula |
| :--- | :--- |
| **Revenue** | $\text{Units Sold} \times \text{Price per Unit}$ |
| **Operating Profit** | $\text{Revenue} \times \text{Operating Margin}$ |
| **Total Expenses** | $\text{Revenue} \times (1 - \text{Operating Margin})$ |
| **Unit Cost** | $\text{Price per Unit} \times (1 - \text{Operating Margin})$ |

### Business Questions

- What product category (product) had the highest sales (in dollars) in 2021? How much did it sell?
- What state had the highest sales (in dollars) of women's products in 2021? How much was it?
- What state had the highest sales (in dollars) of men's products in 2021? How much was it?
- What retailer purchased the most units in 2021? In 2020?

In [270]:
df_clean['REVENUE'] = (df_clean['UNITS_SOLD'] * df_clean['PRICE_PER_UNIT'])

In [271]:
highest_product_sales_2021 = df_clean[df_clean['INVOICE_DATE_VERIFIED'].dt.year == 2021].groupby('PRODUCT_NAME')['REVENUE'].cumsum()

In [272]:
highest_state_sales_2021 = df_clean[df_clean['INVOICE_DATE_VERIFIED'].dt.year == 2021].groupby('STATE')['REVENUE'].cumsum()

In [273]:
womens_products_filter = df_clean['PRODUCT_NAME'].str.contains(r'\bwomen\b', case=False, na=False)
womens_products_filter

0        False
1        False
2        False
3        False
4        False
         ...
10266     True
10267     True
10268     True
10269     True
10270     True
Name: PRODUCT_NAME, Length: 10268, dtype: bool

In [274]:
# womens_sales = pd.merge(highest_product_sales_2021, womens_products_filter)

In [275]:
mens_products_filter = df_clean['PRODUCT_NAME'].str.contains(r'\bmen\b', case=False, na=False)
mens_products_filter

0         True
1         True
2         True
3         True
4         True
         ...
10266    False
10267    False
10268    False
10269    False
10270    False
Name: PRODUCT_NAME, Length: 10268, dtype: bool

In [276]:
# mens_sales = pd.merge(highest_product_sales_2021, mens_products_filter)

In [277]:
highest_retailer_purchases = df_clean.groupby('RETAILER')['REVENUE'].sum()
highest_retailer_purchases

RETAILER
Amazon           27962625.0
Foot Locker      53620425.0
Kohl's           10852813.0
Sports Direct    13031410.0
Walmart           2256523.0
West Gear        14584306.0
Name: REVENUE, dtype: float64

### Model Preparation

### Modeling

### Interpretation

## Summary